CREATE TABLE adaptive_session (
  id              VARCHAR(40) PRIMARY KEY,
  user_id         BIGINT NULL,
  device_id       VARCHAR(64) NOT NULL,
  status          VARCHAR(16) NOT NULL,
  initial_planet  VARCHAR(32) NOT NULL,
  current_planet  VARCHAR(32) NOT NULL,
  paused_reason   VARCHAR(64) NULL,
  seed_source     VARCHAR(16) NOT NULL,
  started_at      DATETIME NOT NULL,
  paused_at       DATETIME NULL,
  ended_at        DATETIME NULL,
  created_at      DATETIME NOT NULL,
  INDEX idx_adaptive_device_created (device_id, created_at),
  INDEX idx_adaptive_status         (status)
);

CREATE TABLE eeg_window (
  id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
  adaptive_session_id   VARCHAR(40) NOT NULL,
  window_index          INT NOT NULL,
  window_start_at       DATETIME NOT NULL,
  window_end_at         DATETIME NOT NULL,
  window_duration_sec   INT NOT NULL,
  sample_count          BIGINT NOT NULL,
  sample_rate_hz        DOUBLE NOT NULL,
  delta                 DOUBLE,
  theta                 DOUBLE,
  alpha                 DOUBLE,
  beta                  DOUBLE,
  gamma                 DOUBLE,
  dominant_band         VARCHAR(16),
  quality_score         DOUBLE,
  signal_ok             TINYINT(1) NOT NULL,
  focus_readiness       DOUBLE,
  stress_load           DOUBLE,
  fatigue_risk          DOUBLE,
  relaxation_level      DOUBLE,
  cortical_arousal      DOUBLE,
  mental_workload       DOUBLE,
  state_label           VARCHAR(64),
  adaptive_action       VARCHAR(32) NOT NULL,
  created_at            DATETIME NOT NULL,
  INDEX idx_eeg_window_session_index (adaptive_session_id, window_index)
);

CREATE TABLE session_segment (
  id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
  adaptive_session_id   VARCHAR(40) NOT NULL,
  segment_index         INT NOT NULL,
  driven_by_window_id   BIGINT NULL,
  planet                VARCHAR(32) NOT NULL,
  params_json           JSON,
  audio_id              VARCHAR(40) NULL,
  status                VARCHAR(16) NOT NULL,
  is_fallback           TINYINT(1) NOT NULL,
  gen_started_at        DATETIME NULL,
  gen_ready_at          DATETIME NULL,
  played_at             DATETIME NULL,
  duration_sec          INT NOT NULL,
  error_code            VARCHAR(40) NULL,
  created_at            DATETIME NOT NULL,
  INDEX idx_session_segment_session_index (adaptive_session_id, segment_index)
);
